services:
  # Game server
  gsserver:
    image: ${HUB_ALIYUN}yulinzhihou/gs_server:latest
    container_name: gsserver
    volumes:
      - "${SHARED_DIR}/:/home"
      # - "${SHARED_DIR}/billing/:/home/billing/"
    ports:
      - "${LOGIN_PORT}:${LOGIN_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${BILLING_PORT}:${BILLING_PORT}"
    restart: ${RESTART}
    links:
      - gsmysql:gsmysql
      - gsnginx:gsnginx
      - gsphp:gsphp
      - gsredis:gsredis
  gsmysql:
    image: ${HUB_ALIYUN}yulinzhihou/gs_mysql51:latest
    container_name: gsmysql
    volumes:
      - "${SHARED_DIR}/gsmysql/:/var/lib/mysql"
      - "${SHARED_DIR}/backup/:/home/backup"
    ports:
      - "${TL_MYSQL_PORT}:3306"
    environment:
      MYSQL_USER: ${TL_MYSQL_USER}
      MYSQL_PASSWORD: ${TL_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TL_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE_TLBBDB: "tlbbdb"
      MYSQL_DATABASE_WEB: "web"
      MYSQL_DATABASE_GSGM: "gs_gmtools"
      TZ: "$TZ"
    restart: ${RESTART}
  # WEBSERVER
  gsnginx:
    image: ${HUB_ALIYUN}yulinzhihou/gs_nginx:latest
    container_name: gsnginx
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_GM_PORT}:81"
      - "${WEB_HTTPS_PORT}:443"
    volumes:
      - ${SHARED_DIR}/www/:/www/:rw
      - ${SHARED_DIR}/ssl/:/ssl:rw # 如果有ssl证书，请放在此目录里面
      - ${SHARED_DIR}/conf.d/:/etc/nginx/conf.d/:rw #新增网站，需要将配置放在此目录
      - ${SHARED_DIR}/log/nginx/:/var/log/nginx/:rw
      - ${SHARED_DIR}/tlbb:/home/tlbb
    environment:
      TZ: "$TZ"
    restart: always
  # PHP
  gsphp:
    image: ${HUB_ALIYUN}yulinzhihou/gs_php:latest
    container_name: gsphp
    volumes:
      - ${SHARED_DIR}/www/:/www/:rw
      - ${SHARED_DIR}/tlbb/:/home/tlbb:rw
      - ${SHARED_DIR}/log/php/:/var/log/php
    restart: always
    cap_add:
      - SYS_PTRACE
  #NOSQL
  gsredis:
    image: ${HUB_ALIYUN}yulinzhihou/gs_redis:latest
    container_name: gsredis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${SHARED_DIR}/redis:/data/:rw
      - ${SHARED_DIR}/redis/:/usr/local/etc/redis/:rw
    restart: always
    environment:
      TZ: "$TZ"
